'use client';

import { Button, Card } from '@shop/ui';
import { useTranslation } from '@/lib/i18n-client';
import {
  adminFilterLabelClass,
  adminFormControlClass,
  adminPaginationNavButtonClass,
  adminSectionSubtitleClass,
  adminSolidButtonClass,
  dashboardCardPadding,
  dashboardEmptyText,
  dashboardSectionTitle,
} from '../components/dashboardUi';
import { AttributeBlock } from './AttributeBlock';
import { useAttributes } from './useAttributes';

export function AttributesPageContent() {
  const { t } = useTranslation();
  const {
    attributes,
    loading,
    showAddForm,
    editingAttribute,
    editingAttributeName,
    savingAttribute,
    expandedAttributes,
    formData,
    newValue,
    addingValueTo,
    deletingValue,
    valueError,
    expandedValueId,
    editingLabel,
    editingColors,
    editingImageUrl,
    savingValue,
    imageUploading,
    fileInputRef,
    setShowAddForm,
    setFormData,
    setNewValue,
    setEditingAttributeName,
    setEditingLabel,
    setEditingColors,
    setEditingImageUrl,
    setValueError,
    handleCreateAttribute,
    handleDeleteAttribute,
    handleUpdateAttributeName,
    toggleAttributeEdit,
    handleAddValue,
    handleDeleteValue,
    toggleValueEdit,
    handleImageUpload,
    handleRemoveImage,
    handleSaveInlineValue,
    toggleExpand,
  } = useAttributes();

  return (
    <>
      <section className="rounded-xl border border-admin-brand-2/18 bg-white p-5 shadow-[0_1px_2px_rgba(47,63,61,0.05),0_8px_24px_-8px_rgba(47,63,61,0.1)] sm:p-6">
        <div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
          <div>
            <h1 className="text-xl font-semibold tracking-tight text-admin-brand">{t('admin.attributes.title')}</h1>
            <p className={`mt-1 max-w-2xl ${adminSectionSubtitleClass}`}>{t('admin.attributes.subtitle')}</p>
          </div>
          <button
            type="button"
            onClick={() => setShowAddForm(!showAddForm)}
            className={`inline-flex shrink-0 items-center justify-center gap-2 rounded-lg px-4 py-2.5 text-sm font-medium ${adminSolidButtonClass}`}
          >
            <svg className="h-5 w-5 shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24" aria-hidden>
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 4v16m8-8H4" />
            </svg>
            {showAddForm ? t('admin.attributes.cancel') : t('admin.attributes.addAttribute')}
          </button>
        </div>
      </section>

      {showAddForm ? (
        <Card variant="admin" className={dashboardCardPadding}>
          <h2 className={`mb-4 ${dashboardSectionTitle}`}>{t('admin.attributes.createNewAttribute')}</h2>
          <form onSubmit={handleCreateAttribute} className="space-y-4">
            <div>
              <label htmlFor="attr-name" className={adminFilterLabelClass}>
                {t('admin.attributes.name')} <span className="text-red-600">{t('admin.attributes.required')}</span>
              </label>
              <input
                id="attr-name"
                type="text"
                value={formData.name}
                onChange={(e) => setFormData({ ...formData, name: e.target.value })}
                placeholder={t('admin.attributes.namePlaceholder')}
                className={`${adminFormControlClass} w-full`}
                required
              />
              <p className={`mt-1.5 ${dashboardEmptyText}`}>{t('admin.attributes.keyAutoGenerated')}</p>
            </div>

            <div className="flex flex-wrap gap-3 border-t border-admin-brand-2/12 pt-4">
              <Button type="submit" variant="primary" size="sm" className={adminSolidButtonClass}>
                {t('admin.attributes.createAttribute')}
              </Button>
              <Button
                type="button"
                variant="outline"
                size="sm"
                onClick={() => {
                  setShowAddForm(false);
                  setFormData({ name: '' });
                }}
                className={adminPaginationNavButtonClass}
              >
                {t('admin.attributes.cancel')}
              </Button>
            </div>
          </form>
        </Card>
      ) : null}

      <Card variant="admin" className={dashboardCardPadding}>
        {loading ? (
          <div className="py-8 text-center">
            <div className="mx-auto mb-3 h-8 w-8 animate-spin rounded-full border-2 border-admin-surface border-b-admin-brand" />
            <p className={dashboardEmptyText}>{t('admin.attributes.loadingAttributes')}</p>
          </div>
        ) : attributes.length === 0 ? (
          <div className="py-10 text-center">
            <div className="mx-auto mb-4 flex h-14 w-14 items-center justify-center rounded-full bg-admin-surface ring-1 ring-inset ring-admin-brand/[0.08]">
              <svg className="h-7 w-7 text-admin-muted" fill="none" stroke="currentColor" viewBox="0 0 24 24" aria-hidden>
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                  d="M7 7h.01M7 3h5c.512 0 1.024.195 1.414.586l7 7a2 2 0 010 2.828l-7 7a2 2 0 01-2.828 0l-7-7A1.994 1.994 0 013 12V7a4 4 0 014-4z"
                />
              </svg>
            </div>
            <h3 className="text-base font-semibold text-admin-brand">{t('admin.attributes.noAttributes')}</h3>
            <p className={`mt-2 ${dashboardEmptyText}`}>{t('admin.attributes.getStarted')}</p>
            <button
              type="button"
              onClick={() => setShowAddForm(true)}
              className={`mt-5 inline-flex items-center justify-center gap-2 rounded-lg px-4 py-2.5 text-sm font-medium ${adminSolidButtonClass}`}
            >
              {t('admin.attributes.createAttribute')}
            </button>
          </div>
        ) : (
          <div className="space-y-3">
            {attributes.map((attribute) => (
              <AttributeBlock
                key={attribute.id}
                attribute={attribute}
                isExpanded={expandedAttributes.has(attribute.id)}
                editingAttribute={editingAttribute}
                editingAttributeName={editingAttributeName}
                savingAttribute={savingAttribute}
                newValue={newValue}
                addingValueTo={addingValueTo}
                deletingValue={deletingValue}
                expandedValueId={expandedValueId}
                editingLabel={editingLabel}
                editingColors={editingColors}
                editingImageUrl={editingImageUrl}
                savingValue={savingValue}
                imageUploading={imageUploading}
                fileInputRef={fileInputRef}
                valueError={valueError}
                t={t}
                onToggleExpand={() => toggleExpand(attribute.id)}
                onEditingNameChange={setEditingAttributeName}
                onSaveName={() => handleUpdateAttributeName(attribute.id)}
                onToggleAttributeEdit={() => toggleAttributeEdit(attribute)}
                onDeleteAttribute={() => handleDeleteAttribute(attribute.id, attribute.name)}
                onNewValueChange={setNewValue}
                onClearValueError={() => setValueError(null)}
                onAddValue={() => handleAddValue(attribute.id)}
                onDeleteValue={(valueId, label) => handleDeleteValue(attribute.id, valueId, label)}
                onToggleValueEdit={(value) => toggleValueEdit(attribute.id, value)}
                onLabelChange={setEditingLabel}
                onColorsChange={setEditingColors}
                onImageUpload={handleImageUpload}
                onRemoveImage={handleRemoveImage}
                onSaveInlineValue={handleSaveInlineValue}
              />
            ))}
          </div>
        )}
      </Card>
    </>
  );
}
