import { processImageUrl } from '@/lib/utils/image-utils';
import { staticAssetHref, toR2Url } from '@/lib/r2-assets';

/** Card / product thumbnail widths generated by optimize-homepage-images.ts */
export const CARD_IMAGE_WIDTHS = [400, 600, 800] as const;
export type CardImageWidth = (typeof CARD_IMAGE_WIDTHS)[number];

/** Hero responsive widths */
export const HERO_IMAGE_WIDTHS = [768, 1200, 1600] as const;
export type HeroImageWidth = (typeof HERO_IMAGE_WIDTHS)[number];

/** Decorative assets (favorites background) — single compressed width */
export const DECORATIVE_IMAGE_WIDTH = 900;

const OPTIMIZED_SEGMENT = '/assets/optimized/';
const HERO_OPTIMIZED_PREFIX = '/assets/hero/optimized/';

function isAlreadyOptimized(pathOrUrl: string): boolean {
  return (
    pathOrUrl.includes(OPTIMIZED_SEGMENT) ||
    pathOrUrl.includes(HERO_OPTIMIZED_PREFIX) ||
    /-\d+w\.webp$/i.test(pathOrUrl)
  );
}

function stripExtension(path: string): string {
  return path.replace(/\.[^./\\]+$/, '');
}

/** Path key under bucket / public root, without leading slash. */
function extractStorageKey(url: string): string | null {
  const trimmed = url.trim();
  if (!trimmed) return null;

  if (trimmed.startsWith('http://') || trimmed.startsWith('https://')) {
    try {
      return decodeURIComponent(new URL(trimmed).pathname.replace(/^\/+/, ''));
    } catch {
      return null;
    }
  }

  const path = trimmed.startsWith('/') ? trimmed.slice(1) : trimmed;
  return decodeURIComponent(path);
}

function buildOptimizedKey(sourceKey: string, width: number): string {
  const base = stripExtension(sourceKey);
  return `assets/optimized/${base}-${width}w.webp`;
}

function buildHeroOptimizedKey(sourceKey: string, width: number): string {
  const fileName = sourceKey.split('/').pop() ?? 'image';
  const base = stripExtension(fileName);
  return `assets/hero/optimized/${base}-${width}w.webp`;
}

function resolvePublicUrl(relativePath: string): string {
  const path = relativePath.startsWith('/') ? relativePath : `/${relativePath}`;
  return staticAssetHref(toR2Url(path));
}

/**
 * Maps a product / menu R2 URL to a pre-generated WebP card thumbnail.
 * Original: menu/import/deserty/foo.jpg → assets/optimized/menu/import/deserty/foo-400w.webp
 */
export function toOptimizedProductCardUrl(
  url: string | null | undefined,
  width: CardImageWidth = 400,
): string | null {
  const processed = processImageUrl(url ?? null);
  if (!processed) return null;
  if (isAlreadyOptimized(processed)) return processed;
  if (/\.svg$/i.test(processed)) return processed;

  const sourceKey = extractStorageKey(processed);
  if (!sourceKey) return processed;

  const optimizedKey = buildOptimizedKey(sourceKey, width);
  return resolvePublicUrl(`/${optimizedKey}`);
}

/**
 * Maps a static /assets/... path to hero optimized WebP (responsive set uses largest by default).
 */
export function toOptimizedHeroUrl(
  publicPath: string,
  width: HeroImageWidth = 1600,
): string {
  const resolved = staticAssetHref(toR2Url(publicPath));
  if (isAlreadyOptimized(resolved)) return resolved;

  const sourceKey = extractStorageKey(publicPath);
  if (!sourceKey) return resolved;

  const optimizedKey = buildHeroOptimizedKey(sourceKey, width);
  return resolvePublicUrl(`/${optimizedKey}`);
}

/**
 * Compressed decorative background (favorites union pattern).
 */
export function toOptimizedDecorativeUrl(publicPath: string): string {
  const resolved = staticAssetHref(toR2Url(publicPath));
  if (isAlreadyOptimized(resolved)) return resolved;

  const sourceKey = extractStorageKey(publicPath);
  if (!sourceKey) return resolved;

  const optimizedKey = buildOptimizedKey(sourceKey, DECORATIVE_IMAGE_WIDTH);
  return resolvePublicUrl(`/${optimizedKey}`);
}

/** Build srcSet for hero from a public asset path. */
export function buildHeroSrcSet(publicPath: string): string {
  return HERO_IMAGE_WIDTHS.map(
    (w) => `${toOptimizedHeroUrl(publicPath, w)} ${w}w`,
  ).join(', ');
}

export function defaultHeroSrc(publicPath: string): string {
  return toOptimizedHeroUrl(publicPath, 1600);
}

/** Carousel gallery — 800w WebP under assets/optimized/... */
export function toOptimizedCarouselUrl(publicPath: string): string {
  const sourceKey = extractStorageKey(publicPath);
  if (!sourceKey || isAlreadyOptimized(sourceKey)) {
    return resolvePublicUrl(publicPath.startsWith('/') ? publicPath : `/${publicPath}`);
  }

  const segments = sourceKey.split('/');
  const fileName = segments.pop() ?? 'image';
  const base = stripExtension(fileName).replace(/\s+/g, '-');
  const optimizedKey = `assets/optimized/${dir}/${base}-800w.webp`;
  return resolvePublicUrl(`/${optimizedKey}`);
}

/** Card image sizes attribute for homepage product grids. */
export const HOME_PRODUCT_CARD_SIZES = '(max-width: 640px) 45vw, (max-width: 1024px) 200px, 223px';
