import { processImageUrl } from '@/lib/utils/image-utils';
import { staticAssetHref, toR2Url } from '@/lib/r2-assets';
import {
  getSourceForOptimizedKey,
  isOptimizedKeyAvailable,
} from '@/lib/image-optimization-manifest';

/** Card / product thumbnail widths generated by optimize scripts */
export const CARD_IMAGE_WIDTHS = [400, 600, 800] as const;
export type CardImageWidth = (typeof CARD_IMAGE_WIDTHS)[number];

/** Hero responsive widths */
export const HERO_IMAGE_WIDTHS = [768, 1200, 1600] as const;
export type HeroImageWidth = (typeof HERO_IMAGE_WIDTHS)[number];

/** Decorative assets (favorites background) — single compressed width */
export const DECORATIVE_IMAGE_WIDTH = 900;

const OPTIMIZED_SEGMENT = '/assets/optimized/';
const HERO_OPTIMIZED_PREFIX = '/assets/hero/optimized/';
const CAROUSEL_OPTIMIZED_WIDTH = 800;

function getR2PublicBase(): string {
  return process.env.NEXT_PUBLIC_R2_PUBLIC_BASE_URL?.trim().replace(/\/+$/, '') ?? '';
}

function isAlreadyOptimized(pathOrUrl: string): boolean {
  return (
    pathOrUrl.includes(OPTIMIZED_SEGMENT) ||
    pathOrUrl.includes(HERO_OPTIMIZED_PREFIX) ||
    /-\d+w\.webp$/i.test(pathOrUrl)
  );
}

function stripExtension(path: string): string {
  return path.replace(/\.[^./\\]+$/, '');
}

/** Path key under bucket / public root, without leading slash. */
function extractStorageKey(url: string): string | null {
  const trimmed = url.trim();
  if (!trimmed) return null;

  if (trimmed.startsWith('http://') || trimmed.startsWith('https://')) {
    try {
      return decodeURIComponent(new URL(trimmed).pathname.replace(/^\/+/, ''));
    } catch {
      return null;
    }
  }

  const path = trimmed.startsWith('/') ? trimmed.slice(1) : trimmed;
  return decodeURIComponent(path);
}

function buildOptimizedKey(sourceKey: string, width: number): string {
  const base = stripExtension(sourceKey);
  return `assets/optimized/${base}-${width}w.webp`;
}

function buildHeroOptimizedKey(sourceKey: string, width: number): string {
  const fileName = sourceKey.split('/').pop() ?? 'image';
  const base = stripExtension(fileName);
  return `assets/hero/optimized/${base}-${width}w.webp`;
}

function buildCarouselOptimizedKey(sourceKey: string): string {
  const segments = sourceKey.split('/');
  const fileName = segments.pop() ?? 'image';
  const dir = segments.join('/');
  const base = stripExtension(fileName).replace(/\s+/g, '-');
  return `assets/optimized/${dir}/${base}-${CAROUSEL_OPTIMIZED_WIDTH}w.webp`;
}

function normalizeAssetPath(pathOrUrl: string): string {
  if (pathOrUrl.startsWith('http://') || pathOrUrl.startsWith('https://')) {
    return pathOrUrl;
  }
  return pathOrUrl.startsWith('/') ? pathOrUrl : `/${pathOrUrl}`;
}

/** Original asset URL/path safe for `<Image src>` — never a missing local optimized path. */
function resolveOriginalAssetUrl(pathOrUrl: string): string {
  if (pathOrUrl.startsWith('http://') || pathOrUrl.startsWith('https://')) {
    return pathOrUrl;
  }
  return staticAssetHref(toR2Url(normalizeAssetPath(pathOrUrl)));
}

function resolveOptimizedR2Url(optimizedKey: string): string | null {
  if (!isOptimizedKeyAvailable(optimizedKey)) return null;
  if (!getR2PublicBase()) return null;
  return staticAssetHref(toR2Url(`/${optimizedKey}`));
}

function resolveOptimizedOrOriginal(
  optimizedKey: string,
  originalPathOrUrl: string,
): string {
  const optimized = resolveOptimizedR2Url(optimizedKey);
  if (optimized) return optimized;
  return resolveOriginalAssetUrl(originalPathOrUrl);
}

function resolveAlreadyOptimizedUrl(pathOrUrl: string): string {
  const key = extractStorageKey(pathOrUrl);
  if (key && isOptimizedKeyAvailable(key)) {
    const r2Url = resolveOptimizedR2Url(key);
    if (r2Url) return r2Url;
    const source = getSourceForOptimizedKey(key);
    if (source) return resolveOriginalAssetUrl(source);
  }
  if (isAlreadyOptimized(pathOrUrl)) {
    const source = key ? getSourceForOptimizedKey(key) : undefined;
    if (source) return resolveOriginalAssetUrl(source);
  }
  return resolveOriginalAssetUrl(pathOrUrl);
}

/**
 * Maps a product / menu R2 URL to a pre-generated WebP card thumbnail when available.
 * Falls back to the original image URL when env or optimized asset is missing.
 */
export function toOptimizedProductCardUrl(
  url: string | null | undefined,
  width: CardImageWidth = 400,
): string | null {
  const processed = processImageUrl(url ?? null);
  if (!processed) return null;
  if (/\.svg$/i.test(processed)) return processed;
  if (isAlreadyOptimized(processed)) {
    return resolveAlreadyOptimizedUrl(processed);
  }

  const sourceKey = extractStorageKey(processed);
  if (!sourceKey) return processed;

  const optimizedKey = buildOptimizedKey(sourceKey, width);
  return resolveOptimizedOrOriginal(optimizedKey, processed);
}

/**
 * Maps a static /assets/... path to hero optimized WebP when available.
 */
export function toOptimizedHeroUrl(
  publicPath: string,
  width: HeroImageWidth = 1600,
): string {
  const original = resolveOriginalAssetUrl(publicPath);
  if (isAlreadyOptimized(publicPath)) {
    return resolveAlreadyOptimizedUrl(publicPath);
  }

  const sourceKey = extractStorageKey(publicPath);
  if (!sourceKey) return original;

  const optimizedKey = buildHeroOptimizedKey(sourceKey, width);
  return resolveOptimizedOrOriginal(optimizedKey, publicPath);
}

/**
 * Compressed decorative background (favorites union pattern).
 */
export function toOptimizedDecorativeUrl(publicPath: string): string {
  const original = resolveOriginalAssetUrl(publicPath);
  if (isAlreadyOptimized(publicPath)) {
    return resolveAlreadyOptimizedUrl(publicPath);
  }

  const sourceKey = extractStorageKey(publicPath);
  if (!sourceKey) return original;

  const optimizedKey = buildOptimizedKey(sourceKey, DECORATIVE_IMAGE_WIDTH);
  return resolveOptimizedOrOriginal(optimizedKey, publicPath);
}

/** Build srcSet for hero from a public asset path. */
export function buildHeroSrcSet(publicPath: string): string {
  return HERO_IMAGE_WIDTHS.map(
    (w) => `${toOptimizedHeroUrl(publicPath, w)} ${w}w`,
  ).join(', ');
}

export function defaultHeroSrc(publicPath: string): string {
  return toOptimizedHeroUrl(publicPath, 1600);
}

/** Carousel gallery — 800w WebP under assets/optimized/... */
export function toOptimizedCarouselUrl(publicPath: string): string {
  const normalized = normalizeAssetPath(publicPath);
  const original = resolveOriginalAssetUrl(normalized);

  const sourceKey = extractStorageKey(normalized);
  if (!sourceKey) return original;
  if (isAlreadyOptimized(normalized)) {
    return resolveAlreadyOptimizedUrl(normalized);
  }

  const optimizedKey = buildCarouselOptimizedKey(sourceKey);
  return resolveOptimizedOrOriginal(optimizedKey, normalized);
}

/** Card image sizes attribute for homepage product grids. */
export const HOME_PRODUCT_CARD_SIZES = '(max-width: 640px) 45vw, (max-width: 1024px) 200px, 223px';

const LOCAL_MENU_OPTIMIZED_PREFIX = '/assets/optimized/menu/import/';

function isLocalMenuOptimizedPath(pathOrUrl: string): boolean {
  return (
    pathOrUrl.startsWith(LOCAL_MENU_OPTIMIZED_PREFIX) ||
    pathOrUrl.startsWith('assets/optimized/menu/import/')
  );
}

/**
 * Normalizes category sidebar / preview image src for Next/Image.
 * Never returns a broken local `/assets/optimized/menu/import/...` path.
 */
export function normalizeCategoryImageSrc(
  url: string | null | undefined,
): string | null {
  const processed = processImageUrl(url ?? null);
  if (!processed) return null;

  if (isLocalMenuOptimizedPath(processed)) {
    const path = processed.startsWith('/') ? processed : `/${processed}`;
    if (getR2PublicBase()) {
      return staticAssetHref(toR2Url(path));
    }
    const key = extractStorageKey(path);
    const source = key ? getSourceForOptimizedKey(key) : undefined;
    if (source) return resolveOriginalAssetUrl(source);
    return null;
  }

  return toOptimizedProductCardUrl(processed) ?? processed;
}
